### ISSUE TITLE
Write JUnit-compatible XML output on Circle

### ISSUE THREAD

**Issue by gabebw** [gabebw/croniker#101]
Use this HSpec formatter: https://github.com/worksap-ate/hspec-jenkins

Store the test results: https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by gabebw** [comment]
Sadly, `hspec-jenkins` doesn't build with `hspec-core-2.6.0` from LTS 13.0:

<details>
<pre>
    Configuring hspec-jenkins-0.1.1...
    Preprocessing library for hspec-jenkins-0.1.1..
    Building library for hspec-jenkins-0.1.1..
    [1 of 1] Compiling Test.Hspec.Formatters.Jenkins ( lib/Test/Hspec/Formatters/Jenkins.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Test/Hspec/Formatters/Jenkins.o )

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:49:7: error:
        • Couldn't match type ‘hspec-core-2.6.0:Test.Hspec.Core.Formatters.Free.Free
                                 hspec-core-2.6.0:Test.Hspec.Core.Formatters.Monad.FormatF ()’
                         with ‘String -> FormatM ()’
          Expected type: String -> FormatM ()
            Actual type: FormatM ()
        • In a stmt of a 'do' block:
            writeLine $ renderMarkup $ testcase path ""
          In the expression: do writeLine $ renderMarkup $ testcase path ""
          In the ‘exampleSucceeded’ field of a record
       |
    49 |       writeLine $ renderMarkup $
       |       ^^^^^^^^^^^^^^^^^^^^^^^^^^...

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:52:7: error:
        • Couldn't match type ‘hspec-core-2.6.0:Test.Hspec.Core.Formatters.Free.Free
                                 hspec-core-2.6.0:Test.Hspec.Core.Formatters.Monad.FormatF ()’
                         with ‘FailureReason -> FormatM ()’
          Expected type: FailureReason -> FormatM ()
            Actual type: FormatM ()
        • In a stmt of a 'do' block:
            writeLine
              $ renderMarkup
                  $ testcase path
                      $ failure ! message (either formatException id err) $ ""
          In the expression:
            do writeLine
                 $ renderMarkup
                     $ testcase path
                         $ failure ! message (either formatException id err) $ ""
          In the ‘exampleFailed’ field of a record
       |
    52 |       writeLine $ renderMarkup $
       |       ^^^^^^^^^^^^^^^^^^^^^^^^^^...

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:54:56: error:
        • Couldn't match type ‘[Char]’
                         with ‘Either GHC.Exception.Type.SomeException String’
          Expected type: Either GHC.Exception.Type.SomeException String
            Actual type: String
        • In the third argument of ‘either’, namely ‘err’
          In the first argument of ‘message’, namely
            ‘(either formatException id err)’
          In the second argument of ‘(!)’, namely
            ‘message (either formatException id err)’
       |
    54 |           failure ! message (either formatException id err) $ ""
       |                                                        ^^^

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:56:7: error:
        • Couldn't match type ‘hspec-core-2.6.0:Test.Hspec.Core.Formatters.Free.Free
                                 hspec-core-2.6.0:Test.Hspec.Core.Formatters.Monad.FormatF ()’
                         with ‘Maybe String -> FormatM ()’
          Expected type: Maybe String -> FormatM ()
            Actual type: FormatM ()
        • In a stmt of a 'do' block:
            writeLine
              $ renderMarkup
                  $ testcase path
                      $ case mdesc of
                          Just desc -> skipped ! message desc $ ""
                          Nothing -> skipped ""
          In the expression:
            do writeLine
                 $ renderMarkup
                     $ testcase path
                         $ case mdesc of
                             Just desc -> skipped ! message desc $ ""
                             Nothing -> skipped ""
          In the ‘examplePending’ field of a record
       |
    56 |       writeLine $ renderMarkup $
       |       ^^^^^^^^^^^^^^^^^^^^^^^^^^...

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:59:13: error:
        • Couldn't match type ‘Maybe String’ with ‘[Char]’
          Expected type: String
            Actual type: Maybe String
        • In the pattern: Just desc
          In a case alternative: Just desc -> skipped ! message desc $ ""
          In the second argument of ‘($)’, namely
            ‘case mdesc of
               Just desc -> skipped ! message desc $ ""
               Nothing -> skipped ""’
       |
    59 |             Just desc -> skipped ! message desc  $ ""
       |             ^^^^^^^^^

    /private/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gn/T/stack-47e27e7a0a37e5bc/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:60:13: error:
        • Couldn't match type ‘Maybe a0’ with ‘[Char]’
          Expected type: String
            Actual type: Maybe a0
        • In the pattern: Nothing
          In a case alternative: Nothing -> skipped ""
          In the second argument of ‘($)’, namely
            ‘case mdesc of
               Just desc -> skipped ! message desc $ ""
               Nothing -> skipped ""’
       |
    60 |             Nothing -> skipped ""
       |             ^^^^^^^
</pre>
</details>
